spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
         git:
           uri: "https://github.com/ThureinH-cloud/microservices-config.git"
           default-label: "main"
           timeout: 5
           clone-on-start: true
           force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
server:
  port: 8071